language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - export APP_ENV=travis
  - composer install
  - php artisan test:db

script: php artisan test

deploy:
  provider: heroku
  api_key: 6e9b9101-5f55-4547-ab08-4f7bd6c5bf75
  on: master
  run:
    php artisan migrate --force
